ci: work around actions/cache and `cargo install` bugs
For actions/cache it appears that cache-hit wasn't being set to true
when cache hits did occur and for `cargo install` it errors out when a
target is already installed, but doesn't appear to have the same
behavior when run locally.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -160,8 +160,9 @@ jobs:
         components: rustfmt
 
     - name: Install cargo-criterion
-      if: steps.cache.outputs.cache-hit != 'true'
-      run: cargo install cargo-criterion
+      run: |
+        # ignore return value since `cargo install` errors out when already installed
+        cargo install cargo-criterion || true
 
     - name: Build
       run: cargo criterion --no-run
